_target_: mini_latent_pd.flow_matching_module.FlowMatching

model:
  _target_: mini_latent_pd.models.unet.UNet
  in_channels: 1
  out_channels: 1
  model_channels: 64
  time_dim: 256
  num_classes: 10

alpha_beta_scheduler:
  _target_: mini_latent_pd.modules.schedulers.LinearScheduler
  data_dim: 4

sampler:
  _target_: mini_latent_pd.modules.samplers.GaussianSampler
  target_shape: [1, 28, 28]

ode_solver:
  _target_: mini_latent_pd.modules.solvers.EulerSolver

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
