_target_: mini_latent_pd.flow_matching_module.FlowMatching

model:
  _target_: mini_latent_pd.models.mlp.MoonsNet
  input_dim: 2
  output_dim: 2
  hidden_dim: 128
  time_dim: 16
  num_classes: 11

alpha_beta_scheduler:
  _target_: mini_latent_pd.modules.schedulers.LinearScheduler
  data_dim: 2  # 2D data for moons

sampler:
  _target_: mini_latent_pd.modules.samplers.GaussianSampler
  target_shape: [2]  # 2D data points

ode_solver:
  _target_: mini_latent_pd.modules.solvers.EulerSolver

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
