# sweep_config.yaml
method: bayes
program: src/mini_latent_pd/train.py
metric:
  name: val_loss
  goal: minimize
parameters:
  model.optimizer.lr:
    distribution: log_uniform
    min: 0.00001
    max: 1


command:
  - python
  - ${program}
  - ${args_no_hyphens}
  - model=latent_flow
  - trainer.max_epochs=1
project: 'latent_flow'
run_cap: 3